### ISSUE TITLE
Randomisation

### ISSUE THREAD

**Issue by ch-williamson** [nestauk/asf_boiler_optimisation_rct_loop#4]
https://github.com/nestauk/asf_boiler_optimisation_rct_loop/blob/23ef04be686d272c286d6eaf13b56283d5f597d6/2_Code/1_Randomisation_v1_030123.R#L52

Just to check - you don't mind if different regions or treatment arms have different proportions of email types?

**Comment by Oli-Berry** [comment]
Nope :) I would expect the proportions to be even with the high number of users we have.
